// Generated by 'unplugin-auto-import'
export {}
declare global {
  const CodeExample: typeof import('../../../src/components/CodeExample.astro')['default']
  const Markdown: typeof import('@astrojs/markdown-component')['default']
}
