// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const CodeExample: typeof import("/src/components/CodeExample.astro")["default"];
  const Markdown: typeof import("astro/components")["Markdown"];
}
export {};
