// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const CodeBlock: typeof import('/src/components/CodeBlock.astro')['default']
  const Markdown: typeof import('astro/components')['Markdown']
}
export {}
